apiVersion: v1
kind: Namespace
metadata:
  name: pod-restart-watcher
---
apiVersion: v1
kind: Secret
metadata:
  name: perator-registry
  namespace: pod-restart-watcher
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: # base64 encoded Docker config for your container Registry