apiVersion: v1
kind: Namespace
metadata:
  name: pod-restart-watcher
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-restart-operator-sa
  namespace: pod-restart-watcher

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-restart-watcher-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update", "watch"]

