apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-restart-watcher-binding
subjects:
- kind: ServiceAccount
  name: pod-restart-operator-sa
  namespace: pod-restart-watcher
roleRef:
  kind: ClusterRole
  name: pod-restart-watcher-role
  apiGroup: rbac.authorization.k8s.io
